on:
  workflow_dispatch:
  push:
    branches:
      - main
    
name: Publish tool definitions
jobs:
  test:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java_dist: [temurin]
        # os: [ubuntu-latest, windows-latest, macos-latest, macos-latest-xlarge]
        # java_dist: [temurin, zulu, adopt, liberica, microsoft, corretto, semeru, oracle, dragonwell]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.java_dist }}
        java-version: 11
    - name: Check
      run: |
        javac OSArchTest.java
        java OSArchTest >> $GITHUB_STEP_SUMMARY
      shell: bash